<<<<<<< HEAD
/**
 * codegen.ts
 * Core code generation engine: converts a StyleModel into a compact,
 * compatible Java/Android string. This module is pure TypeScript with no
 * DOM dependencies so it can be unit tested easily.
 *
 * Implementation notes:
 *  - Keep generation deterministic and small (use arrays + join)
 *  - Normalize colors to 0xAARRGGBB integers
 *  - Fallbacks provided for invalid inputs
 */

import { StyleModel } from '../types';

function normalizeHex(hex?: string): string {
  if (!hex) return '0xFF000000';
  // Accept #RRGGBB or #AARRGGBB
  const h = hex.replace('#', '');
  if (h.length === 6) return '0xFF' + h.toUpperCase();
  if (h.length === 8) return '0x' + h.toUpperCase();
  return '0xFF000000';
}

export function generateJava(model: StyleModel): string {
  try {
    const lines: string[] = [];
    lines.push('// Generated by SketchWebGen');
    lines.push('android.graphics.drawable.GradientDrawable g = new android.graphics.drawable.GradientDrawable();');
    lines.push(`g.setColor(${normalizeHex(model.color)});`);

    if (model.cornerRadius && model.cornerRadius > 0) {
      lines.push(`g.setCornerRadius(${Math.round(model.cornerRadius)});`);
    }

    if (model.stroke && model.stroke.width && model.stroke.width > 0) {
      lines.push(`g.setStroke(${Math.round(model.stroke.width)}, ${normalizeHex(model.stroke.color)});`);
    }

    // Ripple
    if (model.ripple?.enabled) {
      const rippleColor = normalizeHex(model.ripple.color || '#E0E0E0');
      lines.push(`android.graphics.drawable.RippleDrawable rd = new android.graphics.drawable.RippleDrawable(new android.content.res.ColorStateList(new int[][]{new int[]{}}, new int[]{${rippleColor}}), g, null);`);
      lines.push('view.setBackground(rd);');
    } else {
      lines.push('view.setBackground(g);');
    }

    if (model.clickable) lines.push('view.setClickable(true);');

    if (typeof model.elevation === 'number' && model.elevation > 0) {
      lines.push('int d = (int) (context.getResources().getDisplayMetrics().density);');
      lines.push(`view.setElevation(d * ${Math.round(model.elevation)});`);
    }

    return lines.join('\n');
  } catch (e) {
    return `// Code generation failed: ${(e as Error).message}`;
  }
}
=======
/**
 * codegen.ts
 * Core code generation engine: converts a StyleModel into a compact,
 * compatible Java/Android string. This module is pure TypeScript with no
 * DOM dependencies so it can be unit tested easily.
 *
 * Implementation notes:
 *  - Keep generation deterministic and small (use arrays + join)
 *  - Normalize colors to 0xAARRGGBB integers
 *  - Fallbacks provided for invalid inputs
 */

import { StyleModel } from '../types';

function normalizeHex(hex?: string): string {
  if (!hex) return '0xFF000000';
  // Accept #RRGGBB or #AARRGGBB
  const h = hex.replace('#', '');
  if (h.length === 6) return '0xFF' + h.toUpperCase();
  if (h.length === 8) return '0x' + h.toUpperCase();
  return '0xFF000000';
}

export function generateJava(model: StyleModel): string {
  try {
    const lines: string[] = [];
    lines.push('// Generated by SketchWebGen');
    lines.push('android.graphics.drawable.GradientDrawable g = new android.graphics.drawable.GradientDrawable();');
    lines.push(`g.setColor(${normalizeHex(model.color)});`);

    if (model.cornerRadius && model.cornerRadius > 0) {
      lines.push(`g.setCornerRadius(${Math.round(model.cornerRadius)});`);
    }

    if (model.stroke && model.stroke.width && model.stroke.width > 0) {
      lines.push(`g.setStroke(${Math.round(model.stroke.width)}, ${normalizeHex(model.stroke.color)});`);
    }

    // Ripple
    if (model.ripple?.enabled) {
      const rippleColor = normalizeHex(model.ripple.color || '#E0E0E0');
      lines.push(`android.graphics.drawable.RippleDrawable rd = new android.graphics.drawable.RippleDrawable(new android.content.res.ColorStateList(new int[][]{new int[]{}}, new int[]{${rippleColor}}), g, null);`);
      lines.push('view.setBackground(rd);');
    } else {
      lines.push('view.setBackground(g);');
    }

    if (model.clickable) lines.push('view.setClickable(true);');

    if (typeof model.elevation === 'number' && model.elevation > 0) {
      lines.push('int d = (int) (context.getResources().getDisplayMetrics().density);');
      lines.push(`view.setElevation(d * ${Math.round(model.elevation)});`);
    }

    return lines.join('\n');
  } catch (e) {
    return `// Code generation failed: ${(e as Error).message}`;
  }
}
>>>>>>> e0a9267de792070e0a727aa26d900288ed444b96
